version: '3.4'

networks:
  boardgame:
  message:
  order:
  user:
  gateway:

services:
  ocelot.gw:
    image: ${DOCKER_REGISTRY-}ocelotgw
    build:
      context: .
      dockerfile: MicroServices/Gateway/Ocelot.GW/Dockerfile
    networks:
        - gateway
    depends_on:
        - boardgame.api
        - messages.api
        - order.api
    ports:
        - "5000:8080" 
        - "5000:8081" 

  boardgame.api:
    image: ${DOCKER_REGISTRY-}boardgameapi
    build:
      context: .
      dockerfile: MicroServices/APIs/BoardGame/BoardGame.API/Dockerfile
    networks:
        - boardgame
        - gateway 
    depends_on:
        - boardgame.db
    environment:
        - DB_HOST=boardgame.db
        - DB_DATABASE=BoardGameDb
        - DB_USER=sa
        - DB_MSSQL_SA_PASSWORD=Pwd123!?1
   
  boardgame.db:
    container_name: boardgame.db
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
        - boardgame
    ports:
        - "7000:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Pwd123!?1
        - MSSQL_PID=Developer 

  messages.api:
    image: ${DOCKER_REGISTRY-}messagesapi
    build:
      context: .
      dockerfile: MicroServices/APIs/Messages/Messages.API/Dockerfile
    networks: 
        - message
        - gateway
    depends_on:
        - message.db      
    environment:
        - DB_HOST=message.db
        - DB_DATABASE=MessageDb
        - DB_USER=sa
        - DB_MSSQL_SA_PASSWORD=Pwd123!?1

  message.db:
    container_name: message.db
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
        - message
    ports:
        - "7001:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Pwd123!?1
        - MSSQL_PID=Developer

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: MicroServices/APIs/Order/Order.API/Dockerfile
    networks: 
        - order
        - gateway 
    depends_on:
        - order.db      
    environment:
        - DB_HOST=order.db
        - DB_DATABASE=OrderDb
        - DB_USER=sa
        - DB_MSSQL_SA_PASSWORD=Pwd123!?1

  order.db:
    container_name: order.db
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
        - order
    ports:
        - "7002:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Pwd123!?1
        - MSSQL_PID=Developer
   
  
